# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  pedanticargsidentity:
    image: pedanticargsidentity
    build:
      context: .
      dockerfile: Web/PedanticArgsIdentity/Dockerfile
    ports:
      - 5068:5068
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
